### ISSUE TITLE
Certificate store path cannot be resolved

### ISSUE THREAD

**Issue by Flash1232** [DomiStyle/docker-idrac6#37]
```bash
...
20/01/2022 23:20:30 screen setup finished.
idrac2_1  | 20/01/2022 23:20:30 
idrac2_1  | 
idrac2_1  | The VNC desktop is:      6fbadb7c5a0a:0
idrac2_1  | PORT=5900
idrac2_1  | 
idrac2_1  | ******************************************************************************
idrac2_1  | Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?
idrac2_1  | 
idrac2_1  | The scheme stores pixel data offscreen on the VNC viewer side for faster
idrac2_1  | retrieval.  It should work with any VNC viewer.  Try it by running:
idrac2_1  | 
idrac2_1  |     x11vnc -ncache 10 ...
idrac2_1  | 
idrac2_1  | One can also add -ncache_cr for smooth 'copyrect' window motion.
idrac2_1  | More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching
idrac2_1  | 
idrac2_1  | Extracting avctVMLinux64
idrac2_1  | Initialization complete, starting virtual console
idrac2_1  | Jan 20, 2022 11:20:31 PM java.util.prefs.FileSystemPreferences$1 run
idrac2_1  | WARNING: Couldn't create user preferences directory. User preferences are unusable.
idrac2_1  | Jan 20, 2022 11:20:31 PM java.util.prefs.FileSystemPreferences$1 run
idrac2_1  | WARNING: java.io.IOException: Not a directory
idrac2_1  | 01/20/2022 11:20:31:293: Starting client.
idrac2_1  | ====setPowerMenuStatus: (##2)
idrac2_1  | Video Panel Dimensions: W = 820 H = 620
idrac2_1  | ProtocolAPCP: Request version: 2.37
idrac2_1  | Video Panel Dimensions: W = 820 H = 620
idrac2_1  | 
idrac2_1  | ProtocolAPCP: returned Version [2.34]
idrac2_1  | 
idrac2_1  | Certificate host:idrac-r420.example.com
idrac2_1  | OS: Linux
idrac2_1  | OS Ver: 5.10.89-1-MANJARO
idrac2_1  | m_ksFileName:/dev/null/.java/deployment/security/trusted.certs
idrac2_1  | java.io.FileNotFoundException: /dev/null/.java/deployment/security/trusted.certs (Not a directory)
idrac2_1  | 	at java.io.FileInputStream.open(Native Method)
idrac2_1  | 	at java.io.FileInputStream.<init>(FileInputStream.java:146)
idrac2_1  | 	at com.avocent.kvm.base.util.KVMTrustManager.loadCertificate(Unknown Source)
idrac2_1  | 	at com.avocent.kvm.base.util.KVMTrustManager.<init>(Unknown Source)
idrac2_1  | 	at com.avocent.kvm.avsp.ProtocolAPCP.receiveSessionSetup(Unknown Source)
idrac2_1  | 	at com.avocent.kvm.avsp.ProtocolAPCP.getAvspSocket(Unknown Source)
idrac2_1  | 	at com.avocent.kvm.avsp.ProtocolAPCP.getAvspPrimarySocket(Unknown Source)
idrac2_1  | 	at com.avocent.kvm.avsp.AvspKvmSession.connectToPort(Unknown Source)
idrac2_1  | 	at com.avocent.app.kvm.DefaultViewerMainController.startSession(Unknown Source)
idrac2_1  | 	at com.avocent.idrac.kvm.iDracViewerMainController.startSession(Unknown Source)
idrac2_1  | 	at com.avocent.app.kvm.DefaultViewerMainController.startApp(Unknown Source)
idrac2_1  | 	at com.avocent.idrac.kvm.iDracViewerMainController.startApp(Unknown Source)
idrac2_1  | 	at com.avocent.idrac.kvm.Main.runApp(Unknown Source)
idrac2_1  | 	at com.avocent.idrac.kvm.Main.main(Unknown Source)
```

Notice the `/dev/null/` in the error message. Any ideas? I'm running via docker compose.

**Comment by andrew-s** [comment]
I think this stems from the change to the Zulu-jdk; https://github.com/DomiStyle/docker-idrac6/commit/4af0f047067505428e89ad1e5baeb604668f1214

I swapped back to :v0.5 and my iDracs are working again.

**Comment by ssmoss** [comment]
@Flash1232 does this solve your issue https://github.com/DomiStyle/docker-idrac6/pull/47 ?

**Comment by FoxxMD** [comment]
@Flash1232 

You'll need to build your own Dockerfile to fix this but its an easy fix.

In [`startapp.sh`](https://github.com/DomiStyle/docker-idrac6/blob/5ed551230525eb264d308457ee76d2ad903ecd8c/startapp.sh#L121) add

```
-Duser.home=/config
```

alongside the rest of the java options in `exec java ...` so like:

```
exec java -cp avctKVM.jar -Djava.library.path="./lib" -Duser.home=/config com.avocent.idrac.kvm.Main...
```

**Comment by Flash1232** [comment]
Thanks for your support! I appreciate you coming back to this issue.
However, unfortunately, I again bricked my iDRAC flash memory which means the server is basically noisy scrap metal at this point. I cannot try your suggestions :(
