### ISSUE TITLE
UnknownHostException error message

### ISSUE THREAD

**Issue by warheat1990** [DomiStyle/docker-idrac6#38]
I have this following error message in my docker.

```
Extracting avctVMLinux64
Initialization complete, starting virtual console
KVM/VM Client Version: 5.03.02 (Build 13)
Jan 28, 2022 6:21:59 PM java.util.prefs.FileSystemPreferences$1 run
WARNING: Couldn't create user preferences directory. User preferences are unusable.
Jan 28, 2022 6:21:59 PM java.util.prefs.FileSystemPreferences$1 run
WARNING: java.io.IOException: Not a directory
** Max Size: W = 1280 H = 768
** Window Pref Size: W = 1034 H = 813
** Max Size: W = 1280 H = 768
** Window Pref Size: W = 1034 H = 813
java.net.UnknownHostException: MAN-P-SV-01-E3
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at java.net.Socket.<init>(Socket.java:425)
	at java.net.Socket.<init>(Socket.java:208)
	at com.avocent.d.a.a.a(Unknown Source)
	at com.avocent.d.a.a.a(Unknown Source)
	at com.avocent.d.a.a.b(Unknown Source)
	at com.avocent.d.c.b.a(Unknown Source)
	at com.avocent.a.a.v.g(Unknown Source)
	at com.avocent.a.a.v.a(Unknown Source)
	at com.avocent.app.c.k.m(Unknown Source)
	at com.avocent.app.c.k.d(Unknown Source)
	at com.avocent.idrac.kvm.a.d(Unknown Source)
	at com.avocent.idrac.kvm.Main.a(Unknown Source)
	at com.avocent.idrac.kvm.Main.main(Unknown Source)
CoreSessionListener : connection failed
in CoreSessionListner : fireOnSessionStateChanged 
 KVM session state SESSION_FAILED
Jan 28, 2022 6:22:30 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock User prefs.  Unix error code 20.
Jan 28, 2022 6:22:30 PM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
Jan 28, 2022 6:23:00 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock User prefs.  Unix error code 20.
```

My portainer stack

```
version: '3.1'

services:
  r220:
    image: domistyle/idrac6
    restart: always
    ports:
      - 5801:5800
      - 5901:5900
    secrets:
      - idrac_host
      - idrac_user
      - idrac_password
    volumes:
      - /d/Docker/iDrac/app:/app
      - /d/Docker/iDrac/media:/vmedia
      - /d/Docker/iDrac/screenshots:/screenshots
secrets:
  idrac_host:
    file: /d/Docker/iDrac/idrac_host.txt
  idrac_user:
    file: /d/Docker/iDrac/idrac_user.txt
  idrac_password:
    file: /d/Docker/iDrac/idrac_password.txt
```

EDIT: In case people are wondering why don't I use the built-in HTML5, my firmware/BIOS is very old. I don't want to screw up because there are a lot of bricked unit due to fail firmware update.

**Comment by warheat1990** [comment]
use IP instead of hostname fixed it
