### ISSUE TITLE
Login failed, possibly due to slow network connection.

### ISSUE THREAD

**Issue by jbnels** [DomiStyle/docker-idrac6#54]
I've tried using tiger vnc, chromium, firefox, and chrome.  All on fedora using podman.  I'm also getting an error saying "The Native library for keyboard and mouse support failed to load.

**Comment by jbnels** [comment]
It was built using the dockerfile:
````
FROM jlesage/baseimage-gui:debian-11

ENV APP_NAME="iDRAC 6"  \
    IDRAC_PORT=443      \
    DISPLAY_WIDTH=801   \
    DISPLAY_HEIGHT=621

COPY keycode-hack.c /keycode-hack.c

RUN APP_ICON_URL=https://raw.githubusercontent.com/DomiStyle/docker-idrac6/master/icon.png && \
    install_app_icon.sh "$APP_ICON_URL"

RUN apt-get update && \
    apt-get install -y wget software-properties-common libx11-dev gcc xdotool && \
    wget -nc https://cdn.azul.com/zulu/bin/zulu7.52.0.11-ca-jdk7.0.332-linux_amd64.deb && \
    apt-get install -y ./zulu7.52.0.11-ca-jdk7.0.332-linux_amd64.deb && \
    gcc -o /keycode-hack.so /keycode-hack.c -shared -s -ldl -fPIC && \
    apt-get remove -y gcc software-properties-common && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/* && \
    rm /keycode-hack.c

RUN mkdir /app && \
    chown ${USER_ID}:${GROUP_ID} /app

RUN rm /usr/lib/jvm/zulu-7-amd64/jre/lib/security/java.security

COPY startapp.sh /startapp.sh
COPY mountiso.sh /mountiso.sh

WORKDIR /app
```

podman run command:
`#!/bin/bash
#
```
podman run -d \
  -p 5800:5800 \
  -p 5900:5900 \
  -e IDRAC_HOST=192.168.0.50 \
  -e IDRAC_USER=root \
  -e IDRAC_PASSWORD=superduperpassword \
  -e KEEP_APP_RUNNING=1 \
  idrac:latest`
```

Logs:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing... 
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing... 
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing... 
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing... 
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing... 
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing... 
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing... 
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing... 
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing... 
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing... 
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing... 
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing... 
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing... 
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing... 
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting xvfb...
[xvfb] starting...
Failed to create /config/xdg/cache for shader cache (No such file or directory)---disabling.
[services.d] starting x11vnc...
[services.d] starting logmonitor...
[services.d] starting openbox...
[x11vnc] starting...
[logmonitor] no file to monitor: disabling service...
14/01/2023 08:58:42 passing arg to libvncserver: -rfbport
14/01/2023 08:58:42 passing arg to libvncserver: 5900
14/01/2023 08:58:42 passing arg to libvncserver: -rfbportv6
14/01/2023 08:58:42 passing arg to libvncserver: 5900
14/01/2023 08:58:42 passing arg to libvncserver: -desktop
14/01/2023 08:58:42 passing arg to libvncserver: iDRAC 6
14/01/2023 08:58:42 x11vnc version: 0.9.14 lastmod: 2015-11-14  pid: 703
[openbox] starting...
Failed to create /config/xdg/cache for shader cache (No such file or directory)---disabling.
14/01/2023 08:58:42 Using X display :0
14/01/2023 08:58:42 rootwin: 0x50e reswin: 0x200001 dpy: 0x7e6ada50
14/01/2023 08:58:42 
14/01/2023 08:58:42 ------------------ USEFUL INFORMATION ------------------
14/01/2023 08:58:42 X DAMAGE available on display, using it for polling hints.
14/01/2023 08:58:42   To disable this behavior use: '-noxdamage'
14/01/2023 08:58:42 
14/01/2023 08:58:42   Most compositing window managers like 'compiz' or 'beryl'
14/01/2023 08:58:42   cause X DAMAGE to fail, and so you may not see any screen
14/01/2023 08:58:42   updates via VNC.  Either disable 'compiz' (recommended) or
14/01/2023 08:58:42   supply the x11vnc '-noxdamage' command line option.
14/01/2023 08:58:42 X COMPOSITE available on display, using it for window polling.
14/01/2023 08:58:42   To disable this behavior use: '-noxcomposite'
14/01/2023 08:58:42 
14/01/2023 08:58:42 Wireframing: -wireframe mode is in effect for window moves.
14/01/2023 08:58:42   If this yields undesired behavior (poor response, painting
14/01/2023 08:58:42   errors, etc) it may be disabled:
14/01/2023 08:58:42    - use '-nowf' to disable wireframing completely.
14/01/2023 08:58:42    - use '-nowcr' to disable the Copy Rectangle after the
14/01/2023 08:58:42      moved window is released in the new position.
14/01/2023 08:58:42   Also see the -help entry for tuning parameters.
14/01/2023 08:58:42   You can press 3 Alt_L's (Left "Alt" key) in a row to 
14/01/2023 08:58:42   repaint the screen, also see the -fixscreen option for
14/01/2023 08:58:42   periodic repaints.
14/01/2023 08:58:42 GrabServer control via XTEST.
14/01/2023 08:58:42 
14/01/2023 08:58:42 Scroll Detection: -scrollcopyrect mode is in effect to
14/01/2023 08:58:42   use RECORD extension to try to detect scrolling windows
14/01/2023 08:58:42   (induced by either user keystroke or mouse input).
14/01/2023 08:58:42   If this yields undesired behavior (poor response, painting
14/01/2023 08:58:42   errors, etc) it may be disabled via: '-noscr'
14/01/2023 08:58:42   Also see the -help entry for tuning parameters.
14/01/2023 08:58:42   You can press 3 Alt_L's (Left "Alt" key) in a row to 
14/01/2023 08:58:42   repaint the screen, also see the -fixscreen option for
14/01/2023 08:58:42   periodic repaints.
14/01/2023 08:58:42 
14/01/2023 08:58:42 XKEYBOARD: number of keysyms per keycode 7 is greater
14/01/2023 08:58:42   than 4 and 51 keysyms are mapped above 4.
14/01/2023 08:58:42   Automatically switching to -xkb mode.
14/01/2023 08:58:42   If this makes the key mapping worse you can
14/01/2023 08:58:42   disable it with the "-noxkb" option.
14/01/2023 08:58:42   Also, remember "-remap DEAD" for accenting characters.
14/01/2023 08:58:42 
14/01/2023 08:58:42 X FBPM extension not supported.
Xlib:  extension "DPMS" missing on display ":0".
14/01/2023 08:58:42 X display is not capable of DPMS.
14/01/2023 08:58:42 --------------------------------------------------------
14/01/2023 08:58:42 
14/01/2023 08:58:42 Default visual ID: 0x21
14/01/2023 08:58:42 Read initial data from X display into framebuffer.
14/01/2023 08:58:42 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/3204
14/01/2023 08:58:42 WARNING: Width (801) is not a multiple of 4. VncViewer has problems with that.
14/01/2023 08:58:42 
14/01/2023 08:58:42 X display :0 is 32bpp depth=24 true color
14/01/2023 08:58:42 
14/01/2023 08:58:42 Listening for VNC connections on TCP port 5900
14/01/2023 08:58:42 Listening for VNC connections on TCP6 port 5900
14/01/2023 08:58:42 listen6: bind: Address already in use
14/01/2023 08:58:42 Not listening on IPv6 interface.
14/01/2023 08:58:42 
14/01/2023 08:58:42 Xinerama is present and active (e.g. multi-head).
14/01/2023 08:58:42 Xinerama: number of sub-screens: 1
14/01/2023 08:58:42 Xinerama: no blackouts needed (only one sub-screen)
14/01/2023 08:58:42 
14/01/2023 08:58:42 fb read rate: 1064 MB/sec
14/01/2023 08:58:42 fast read: reset -wait  ms to: 10
14/01/2023 08:58:42 fast read: reset -defer ms to: 10
14/01/2023 08:58:42 The X server says there are 10 mouse buttons.
14/01/2023 08:58:42 screen setup finished.
14/01/2023 08:58:42 

The VNC desktop is:      ce485b00d50c:0
PORT=5900

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

[services.d] starting nginx...
[services.d] starting statusmonitor...
[nginx] starting...
[statusmonitor] no file to monitor: disabling service...
[services.d] starting certsmonitor...
[services.d] starting app...
[app] starting iDRAC 6...
[certsmonitor] disabling service: secure connection not enabled.
Starting
Environment ok
Creating library folder
[services.d] done.
Downloading avctKVM
--2023-01-14 08:58:44--  https://10.0.0.25/software/avctKVM.jar
Connecting to 10.0.0.25:443... connected.
WARNING: The certificate of '10.0.0.25' is not trusted.
WARNING: The certificate of '10.0.0.25' doesn't have a known issuer.
WARNING: The certificate of '10.0.0.25' has expired.
The certificate has expired
The certificate's owner does not match hostname '10.0.0.25'
HTTP request sent, awaiting response... 200 OK
Length: 1006154 (983K) [application/octet-stream]
Saving to: 'avctKVM.jar'

     0K .......... .......... .......... .......... ..........  5%  251K 4s
    50K .......... .......... .......... .......... .......... 10%  316K 3s
   100K .......... .......... .......... .......... .......... 15%  307K 3s
   150K .......... .......... .......... .......... .......... 20%  284K 3s
   200K .......... .......... .......... .......... .......... 25%  310K 3s
   250K .......... .......... .......... .......... .......... 30%  289K 2s
   300K .......... .......... .......... .......... .......... 35%  270K 2s
   350K .......... .......... .......... .......... .......... 40%  315K 2s
   400K .......... .......... .......... .......... .......... 45%  138K 2s
   450K .......... .......... .......... .......... .......... 50%  140K 2s
   500K .......... .......... .......... .......... .......... 55%  156K 2s
   550K .......... .......... .......... .......... .......... 61%  197K 2s
   600K .......... .......... .......... .......... .......... 66%  316K 1s
   650K .......... .......... .......... .......... .......... 71%  313K 1s
   700K .......... .......... .......... .......... .......... 76%  247K 1s
   750K .......... .......... .......... .......... .......... 81%  312K 1s
   800K .......... .......... .......... .......... .......... 86%  307K 1s
   850K .......... .......... .......... .......... .......... 91%  288K 0s
   900K .......... .......... .......... .......... .......... 96%  315K 0s
   950K .......... .......... .......... ..                   100%  315K=3.9s

2023-01-14 08:58:51 (249 KB/s) - 'avctKVM.jar' saved [1006154/1006154]

Downloading avctKVMIOLinux64
--2023-01-14 08:58:51--  https://10.0.0.25/software/avctKVMIOLinux64.jar
Connecting to 10.0.0.25:443... connected.
WARNING: The certificate of '10.0.0.25' is not trusted.
WARNING: The certificate of '10.0.0.25' doesn't have a known issuer.
WARNING: The certificate of '10.0.0.25' has expired.
The certificate has expired
The certificate's owner does not match hostname '10.0.0.25'
HTTP request sent, awaiting response... 200 OK
Length: 983672 (961K) [application/octet-stream]
Saving to: 'lib/avctKVMIOLinux64.jar'

     0K .......... .......... .......... .......... ..........  5%  316K 3s
    50K .......... .......... .......... .......... .......... 10%  255K 3s
   100K .......... .......... .......... .......... .......... 15%  314K 3s
   150K .......... .......... .......... .......... .......... 20%  319K 3s
   200K .......... .......... .......... .......... .......... 26%  276K 2s
   250K .......... .......... .......... .......... .......... 31%  320K 2s
   300K .......... .......... .......... .......... .......... 36%  229K 2s
   350K .......... .......... .......... .......... .......... 41%  258K 2s
   400K .......... .......... .......... .......... .......... 46%  315K 2s
   450K .......... .......... .......... .......... .......... 52%  318K 2s
   500K .......... .......... .......... .......... .......... 57%  277K 1s
   550K .......... .......... .......... .......... .......... 62%  315K 1s
   600K .......... .......... .......... .......... .......... 67%  315K 1s
   650K .......... .......... .......... .......... .......... 72%  109K 1s
   700K .......... .......... .......... .......... .......... 78%  116K 1s
   750K .......... .......... .......... .......... .......... 83%  158K 1s
   800K .......... .......... .......... .......... .......... 88%  315K 0s
   850K .......... .......... .......... .......... .......... 93%  315K 0s
   900K .......... .......... .......... .......... .......... 98%  276K 0s
   950K ..........                                            100%  303K=4.0s

2023-01-14 08:58:56 (242 KB/s) - 'lib/avctKVMIOLinux64.jar' saved [983672/983672]

Downloading avctVMLinux64
--2023-01-14 08:58:56--  https://10.0.0.25/software/avctVMLinux64.jar
Connecting to 10.0.0.25:443... connected.
WARNING: The certificate of '10.0.0.25' is not trusted.
WARNING: The certificate of '10.0.0.25' doesn't have a known issuer.
WARNING: The certificate of '10.0.0.25' has expired.
The certificate has expired
The certificate's owner does not match hostname '10.0.0.25'
HTTP request sent, awaiting response... 200 OK
Length: 135203 (132K) [application/octet-stream]
Saving to: 'lib/avctVMLinux64.jar'

     0K .......... .......... .......... .......... .......... 37%  315K 0s
    50K .......... .......... .......... .......... .......... 75%  314K 0s
   100K .......... .......... .......... ..                   100%  238K=0.5s

2023-01-14 08:58:59 (292 KB/s) - 'lib/avctVMLinux64.jar' saved [135203/135203]

Extracting avctKVMIOLinux64
Extracting avctVMLinux64
[0;32mInitialization complete, starting virtual console[0m
Jan 14, 2023 8:58:59 AM java.util.prefs.FileSystemPreferences$1 run
WARNING: Couldn't create user preferences directory. User preferences are unusable.
Jan 14, 2023 8:58:59 AM java.util.prefs.FileSystemPreferences$1 run
WARNING: java.io.IOException: Not a directory
01/14/2023 08:58:59:885: Starting client.
====setPowerMenuStatus: (##2)

ProtocolAPCP: Version [1.0]

NativeKeyboard.init() Native library loading [jawt]
NativeKeyboard.init() Native library loading [avctKVMIO]
NativeKeyboard.init() Native library loading complete.
01/14/2023 08:59:07:883: NativeKVM: register(com.avocent.kvm.c.pb[windowedVideoPanel,0,0,820x620,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=820,height=620]])
01/14/2023 08:59:07:884: NativeKVM: register(com.avocent.kvm.c.pb[fullScreenVideoPanel,0,0,820x620,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=820,height=620]])
 setPassthroughEnabled(true)
 setPassthroughEnabled(false)
iDracViewerMainController.enableSingleCursorMenuItem() [true]
DefaultMainMenu.setEnabledMenuItem() [Single Cursor]
DefaultMainMenu.setEnabledMenuItem() [Single Cursor]
DefaultMainMenu.setEnabledMenuItem() [Pass all keystrokes to server]
DefaultMainMenu.setEnabledMenuItem() [Pass all keystrokes to server]
01/14/2023 08:59:09:103:  User login response: 3
java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
	at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:430)
	at sun.security.ssl.OutputRecord.write(OutputRecord.java:415)
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:839)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:811)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at com.avocent.kvm.c.d.g.b(Unknown Source)
	at com.avocent.kvm.c.d.i.run(Unknown Source)
Jan 14, 2023 8:59:31 AM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock User prefs.  Unix error code 20.
Jan 14, 2023 8:59:31 AM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
Jan 14, 2023 9:00:01 AM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock User prefs.  Unix error code 20.
Jan 14, 2023 9:00:01 AM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
14/01/2023 09:00:26 Got connection from client 10.88.0.1
14/01/2023 09:00:26   other clients:
14/01/2023 09:00:26 Normal socket connection
14/01/2023 09:00:27 Disabled X server key autorepeat.
14/01/2023 09:00:27   to force back on run: 'xset r on' (3 times)
14/01/2023 09:00:27 incr accepted_client=1 for 10.88.0.1:55032  sock=11
14/01/2023 09:00:27 Client Protocol Version 3.8
14/01/2023 09:00:27 Protocol version sent 3.8, using 3.8
14/01/2023 09:00:27 rfbProcessClientSecurityType: executing handler for type 1
14/01/2023 09:00:27 rfbProcessClientSecurityType: returning securityResult for client rfb version >= 3.8
14/01/2023 09:00:27 copy_tiles: allocating first_line at size 27
14/01/2023 09:00:27 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEC6)
14/01/2023 09:00:27 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x574D5664)
14/01/2023 09:00:27 Enabling full-color cursor updates for client 10.88.0.1
14/01/2023 09:00:27 Enabling X-style cursor updates for client 10.88.0.1
14/01/2023 09:00:27 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0x574D5666)
14/01/2023 09:00:27 Enabling NewFBSize protocol extension for client 10.88.0.1
14/01/2023 09:00:27 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECC)
14/01/2023 09:00:27 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECD)
14/01/2023 09:00:27 Enabling LastRect protocol extension for client 10.88.0.1
14/01/2023 09:00:27 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xC0A1E5CE)
14/01/2023 09:00:27 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEC7)
14/01/2023 09:00:27 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEC8)
14/01/2023 09:00:27 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFEFE)
14/01/2023 09:00:27 Using compression level 2 for client 10.88.0.1
14/01/2023 09:00:27 Using image quality level 8 for client 10.88.0.1
14/01/2023 09:00:27 Using JPEG subsampling 0, Q92 for client 10.88.0.1
14/01/2023 09:00:27 Using tight encoding for client 10.88.0.1
14/01/2023 09:00:27 client_set_net: 10.88.0.1  0.0010
14/01/2023 09:00:27 created   xdamage object: 0x20001e
Jan 14, 2023 9:00:31 AM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock User prefs.  Unix error code 20.
Jan 14, 2023 9:00:31 AM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
[app] starting iDRAC 6...
Starting
Environment ok
Extracting avctKVMIOLinux64
Extracting avctVMLinux64
[0;32mInitialization complete, starting virtual console[0m
Jan 14, 2023 9:00:31 AM java.util.prefs.FileSystemPreferences$1 run
WARNING: Couldn't create user preferences directory. User preferences are unusable.
Jan 14, 2023 9:00:31 AM java.util.prefs.FileSystemPreferences$1 run
WARNING: java.io.IOException: Not a directory
01/14/2023 09:00:31:960: Starting client.
14/01/2023 09:00:36 created selwin: 0x20001f
14/01/2023 09:00:36 called initialize_xfixes()
====setPowerMenuStatus: (##2)

ProtocolAPCP: Version [1.0]

NativeKeyboard.init() Native library loading [jawt]
NativeKeyboard.init() Native library loading [avctKVMIO]
NativeKeyboard.init() Native library loading complete.
01/14/2023 09:00:39:530: NativeKVM: register(com.avocent.kvm.c.pb[windowedVideoPanel,0,0,820x620,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=820,height=620]])
01/14/2023 09:00:39:531: NativeKVM: register(com.avocent.kvm.c.pb[fullScreenVideoPanel,0,0,820x620,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=820,height=620]])
 setPassthroughEnabled(true)
 setPassthroughEnabled(false)
iDracViewerMainController.enableSingleCursorMenuItem() [true]
DefaultMainMenu.setEnabledMenuItem() [Single Cursor]
DefaultMainMenu.setEnabledMenuItem() [Single Cursor]
DefaultMainMenu.setEnabledMenuItem() [Pass all keystrokes to server]
DefaultMainMenu.setEnabledMenuItem() [Pass all keystrokes to server]
01/14/2023 09:00:40:545:  User login response: 3
14/01/2023 09:00:40 client 1 network rate 3573.4 KB/sec (57539.7 eff KB/sec)
14/01/2023 09:00:40 client 1 latency:  0.7 ms
14/01/2023 09:00:40 dt1: 0.0010, dt2: 0.0031 dt3: 0.0007 bytes: 13530
14/01/2023 09:00:40 link_rate: LR_LAN - 1 ms, 3573 KB/s
java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
	at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:430)
	at sun.security.ssl.OutputRecord.write(OutputRecord.java:415)
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:839)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:811)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at com.avocent.kvm.c.d.g.b(Unknown Source)
	at com.avocent.kvm.c.d.i.run(Unknown Source)
Jan 14, 2023 9:00:44 AM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
WARNING: Could not lock User prefs.  Unix error code 20.
Jan 14, 2023 9:00:44 AM java.util.prefs.FileSystemPreferences syncWorld
WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
[app] starting iDRAC 6...
Starting
Environment ok
Extracting avctKVMIOLinux64
Extracting avctVMLinux64
[0;32mInitialization complete, starting virtual console[0m
Jan 14, 2023 9:00:45 AM java.util.prefs.FileSystemPreferences$1 run
WARNING: Couldn't create user preferences directory. User preferences are unusable.
Jan 14, 2023 9:00:45 AM java.util.prefs.FileSystemPreferences$1 run
WARNING: java.io.IOException: Not a directory
01/14/2023 09:00:45:086: Starting client.
14/01/2023 09:00:45 client_count: 0
14/01/2023 09:00:45 Restored X server key autorepeat to: 1
14/01/2023 09:00:45 Client 10.88.0.1 gone
14/01/2023 09:00:45 Statistics             events    Transmit/ RawEquiv ( saved)
14/01/2023 09:00:45  FramebufferUpdate   :     20 |         0/        0 (  0.0%)
14/01/2023 09:00:45  ServerCutText       :      1 |         8/        8 (  0.0%)
14/01/2023 09:00:45  LastRect            :      7 |        84/       84 (  0.0%)
14/01/2023 09:00:45  tight               :    100 |     47916/  3191400 ( 98.5%)
14/01/2023 09:00:45  RichCursor          :      1 |      1374/     1374 (  0.0%)
14/01/2023 09:00:45  TOTALS              :    129 |     49382/  3192866 ( 98.5%)
14/01/2023 09:00:45 Statistics             events    Received/ RawEquiv ( saved)
14/01/2023 09:00:45  PointerEvent        :    292 |      1752/     1752 (  0.0%)
14/01/2023 09:00:45  FramebufferUpdate   :     21 |       210/      210 (  0.0%)
14/01/2023 09:00:45  SetEncodings        :      1 |        92/       92 (  0.0%)
14/01/2023 09:00:45  TOTALS              :    314 |      2054/     2054 (  0.0%)
14/01/2023 09:00:45 destroyed xdamage object: 0x20001e
====setPowerMenuStatus: (##2)
[services.d] stopping services
[services.d] stopping app...
[services.d] stopping certsmonitor...
[services.d] stopping statusmonitor...
[services.d] stopping nginx...
[services.d] stopping openbox...
[services.d] stopping logmonitor...
[services.d] stopping x11vnc...
caught signal: 15
14/01/2023 09:00:50 deleted 26 tile_row polling images.
[services.d] stopping xvfb...
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

iDrac Firmware is 2.92

**Comment by bluknight** [comment]
@jbnels just a sanity check here -- do you have any special characters in your password, or did you try and quote in in a docker-compose manifest or from the command line?  I tried quoting it in my compose file and ran into the same issue you noted here.  Removing the quotes and just giving the password (example:  IDRAC_PASSWORD=jim@bob instead of IDRAC_PASSWORD='jim@bob' solved the issue for me.  Just want to make certain you aren't running into the same problem.
