### ISSUE TITLE
Getting SSL handshake failures with iDRAC 6

### ISSUE THREAD

**Issue by danielcbit** [DomiStyle/docker-idrac6#68]
I'm trying to get this to run but whenever the container starts I get an error relates to the SSL handshake in the logs:

```
2024-03-14T19:59:21.444194367Z Initialization complete, starting virtual console
2024-03-14T19:59:21.813312766Z KVM/VM Client Version: 5.04.04 (Build 488)
2024-03-14T19:59:26.946567544Z Mar 14, 2024 7:59:26 PM java.util.prefs.FileSystemPreferences$1 run
2024-03-14T19:59:26.946593562Z WARNING: Couldn't create user preferences directory. User preferences are unusable.
2024-03-14T19:59:26.947312687Z Mar 14, 2024 7:59:26 PM java.util.prefs.FileSystemPreferences$1 run
2024-03-14T19:59:26.947327532Z WARNING: java.io.IOException: Not a directory
2024-03-14T19:59:26.949927479Z replace numpad
2024-03-14T19:59:27.138402355Z ** Max Size: W = 801 H = 621
2024-03-14T19:59:27.145869247Z ** Window Pref Size: W = 1034 H = 813
2024-03-14T19:59:27.146332557Z ** Max Size: W = 801 H = 621
2024-03-14T19:59:27.146756300Z ** Window Pref Size: W = 1034 H = 813
2024-03-14T19:59:27.269010315Z ProtocolAPCP.receieveSessionSetup : reconType = 101
2024-03-14T19:59:27.276892090Z capabilities..4
2024-03-14T19:59:27.280239145Z the cipher suite is provided by the config
2024-03-14T19:59:27.280362741Z 
2024-03-14T19:59:27.280372204Z Supported protocols: [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2]
2024-03-14T19:59:27.280377650Z 
2024-03-14T19:59:27.280429806Z Enabled protocols: [SSLv3, TLSv1, TLSv1.1, TLSv1.2]
2024-03-14T19:59:27.280437285Z 
2024-03-14T19:59:27.280533927Z Supported ciphers: [TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV, TLS_DH_anon_WITH_AES_256_GCM_SHA384, TLS_DH_anon_WITH_AES_128_GCM_SHA256, TLS_DH_anon_WITH_AES_256_CBC_SHA256, TLS_DH_anon_WITH_AES_256_CBC_SHA, TLS_DH_anon_WITH_AES_128_CBC_SHA256, TLS_DH_anon_WITH_AES_128_CBC_SHA, SSL_DH_anon_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_RC4_128_SHA, SSL_RSA_WITH_RC4_128_MD5, SSL_DH_anon_WITH_RC4_128_MD5, SSL_RSA_WITH_DES_CBC_SHA, SSL_DHE_RSA_WITH_DES_CBC_SHA, SSL_DHE_DSS_WITH_DES_CBC_SHA, SSL_DH_anon_WITH_DES_CBC_SHA, SSL_RSA_EXPORT_WITH_RC4_40_MD5, SSL_DH_anon_EXPORT_WITH_RC4_40_MD5, SSL_RSA_EXPORT_WITH_DES40_CBC_SHA, SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA, SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA, SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA, TLS_RSA_WITH_NULL_SHA256, SSL_RSA_WITH_NULL_SHA, SSL_RSA_WITH_NULL_MD5, TLS_KRB5_WITH_3DES_EDE_CBC_SHA, TLS_KRB5_WITH_3DES_EDE_CBC_MD5, TLS_KRB5_WITH_RC4_128_SHA, TLS_KRB5_WITH_RC4_128_MD5, TLS_KRB5_WITH_DES_CBC_SHA, TLS_KRB5_WITH_DES_CBC_MD5, TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA, TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5, TLS_KRB5_EXPORT_WITH_RC4_40_SHA, TLS_KRB5_EXPORT_WITH_RC4_40_MD5]
2024-03-14T19:59:27.280556556Z 
2024-03-14T19:59:27.280683092Z Enabled ciphers: [TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV, TLS_DH_anon_WITH_AES_256_GCM_SHA384, TLS_DH_anon_WITH_AES_128_GCM_SHA256, TLS_DH_anon_WITH_AES_256_CBC_SHA256, TLS_DH_anon_WITH_AES_256_CBC_SHA, TLS_DH_anon_WITH_AES_128_CBC_SHA256, TLS_DH_anon_WITH_AES_128_CBC_SHA, SSL_DH_anon_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_RC4_128_SHA, SSL_RSA_WITH_RC4_128_MD5, SSL_DH_anon_WITH_RC4_128_MD5, SSL_RSA_WITH_DES_CBC_SHA, SSL_DHE_RSA_WITH_DES_CBC_SHA, SSL_DHE_DSS_WITH_DES_CBC_SHA, SSL_DH_anon_WITH_DES_CBC_SHA, SSL_RSA_EXPORT_WITH_RC4_40_MD5, SSL_DH_anon_EXPORT_WITH_RC4_40_MD5, SSL_RSA_EXPORT_WITH_DES40_CBC_SHA, SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA, SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA, SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA, TLS_RSA_WITH_NULL_SHA256, SSL_RSA_WITH_NULL_SHA, SSL_RSA_WITH_NULL_MD5, TLS_KRB5_WITH_3DES_EDE_CBC_SHA, TLS_KRB5_WITH_3DES_EDE_CBC_MD5, TLS_KRB5_WITH_RC4_128_SHA, TLS_KRB5_WITH_RC4_128_MD5, TLS_KRB5_WITH_DES_CBC_SHA, TLS_KRB5_WITH_DES_CBC_MD5, TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA, TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5, TLS_KRB5_EXPORT_WITH_RC4_40_SHA, TLS_KRB5_EXPORT_WITH_RC4_40_MD5]
2024-03-14T19:59:27.280695026Z 
2024-03-14T19:59:27.285261369Z javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
2024-03-14T19:59:27.285334614Z 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
2024-03-14T19:59:27.285390917Z 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
2024-03-14T19:59:27.285398848Z 	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1970)
2024-03-14T19:59:27.285459085Z 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1087)
2024-03-14T19:59:27.285467084Z 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1323)
2024-03-14T19:59:27.285518873Z 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1350)
2024-03-14T19:59:27.285526621Z 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1334)
2024-03-14T19:59:27.285581629Z 	at com.avocent.d.a.a.a(Unknown Source)
2024-03-14T19:59:27.285589371Z 	at com.avocent.d.a.a.a(Unknown Source)
2024-03-14T19:59:27.285594481Z 	at com.avocent.d.a.a.c(Unknown Source)
2024-03-14T19:59:27.285644284Z 	at com.avocent.d.d.b.a(Unknown Source)
2024-03-14T19:59:27.285651938Z 	at com.avocent.a.b.w.g(Unknown Source)
2024-03-14T19:59:27.285701879Z 	at com.avocent.a.b.w.a(Unknown Source)
2024-03-14T19:59:27.285709402Z 	at com.avocent.app.c.l.m(Unknown Source)
2024-03-14T19:59:27.285714441Z 	at com.avocent.app.c.l.e(Unknown Source)
2024-03-14T19:59:27.285762482Z 	at com.avocent.idrac.kvm.a.e(Unknown Source)
2024-03-14T19:59:27.285770201Z 	at com.avocent.idrac.kvm.Main.a(Unknown Source)
2024-03-14T19:59:27.285832666Z 	at com.avocent.idrac.kvm.Main.main(Unknown Source)
2024-03-14T19:59:27.285840482Z javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
2024-03-14T19:59:27.285883631Z 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
2024-03-14T19:59:27.285891100Z 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
2024-03-14T19:59:27.285945617Z 	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1970)
2024-03-14T19:59:27.285953396Z 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1087)
2024-03-14T19:59:27.286001743Z 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1323)
2024-03-14T19:59:27.286009525Z 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1350)
2024-03-14T19:59:27.286070506Z 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1334)
2024-03-14T19:59:27.286078298Z 	at com.avocent.d.a.a.a(Unknown Source)
2024-03-14T19:59:27.286083468Z 	at com.avocent.d.a.a.a(Unknown Source)
2024-03-14T19:59:27.286131899Z 	at com.avocent.d.a.a.c(Unknown Source)
2024-03-14T19:59:27.286139359Z 	at com.avocent.d.d.b.a(Unknown Source)
2024-03-14T19:59:27.286188808Z 	at com.avocent.a.b.w.g(Unknown Source)
2024-03-14T19:59:27.286196213Z 	at com.avocent.a.b.w.a(Unknown Source)
2024-03-14T19:59:27.286240948Z 	at com.avocent.app.c.l.m(Unknown Source)
2024-03-14T19:59:27.286248290Z 	at com.avocent.app.c.l.e(Unknown Source)
2024-03-14T19:59:27.286328329Z 	at com.avocent.idrac.kvm.a.e(Unknown Source)
2024-03-14T19:59:27.286337618Z 	at com.avocent.idrac.kvm.Main.a(Unknown Source)
2024-03-14T19:59:27.286342809Z 	at com.avocent.idrac.kvm.Main.main(Unknown Source)
2024-03-14T19:59:27.286397818Z CoreSessionListener : connection failed
2024-03-14T19:59:27.286451758Z in CoreSessionListner : fireOnSessionStateChanged 
2024-03-14T19:59:27.286498082Z  KVM session state SESSION_FAILED
2024-03-14T19:59:58.496422070Z Mar 14, 2024 7:59:58 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
2024-03-14T19:59:58.496444607Z WARNING: Could not lock User prefs.  Unix error code 20.
2024-03-14T19:59:58.496906077Z Mar 14, 2024 7:59:58 PM java.util.prefs.FileSystemPreferences syncWorld
2024-03-14T19:59:58.496917961Z WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
2024-03-14T20:00:28.496075065Z Mar 14, 2024 8:00:28 PM java.util.prefs.FileSystemPreferences checkLockFile0ErrorCode
2024-03-14T20:00:28.496105009Z WARNING: Could not lock User prefs.  Unix error code 20.
2024-03-14T20:00:28.496565347Z Mar 14, 2024 8:00:28 PM java.util.prefs.FileSystemPreferences syncWorld
2024-03-14T20:00:28.496578948Z WARNING: Couldn't flush user prefs: java.util.prefs.BackingStoreException: Couldn't get file lock.
```

My iDRAC ver is `2.85.85.85`

I tried running the latest and the v0.8 versions, both with the same outcome

**Comment by NotFluffy** [comment]
I had to go back to v0.7 for mine to work.

**Comment by hmeagher** [comment]
Did you get it to work?  I'm having the same issue.  Can't figure it out.

**Comment by ilium007** [comment]
Still looking for a solution here as well

**Comment by turbo2ltr** [comment]
Same here. I think this project is pretty dead unfortunately.
